import Image from "next/image";
import momentix_transparent_logo from "@/app/assets/momentix_transparent_logo.svg";
import login_vector from "@/app/assets/login_vector.png";
import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {/* Main content */}

        <div className="flex flex-col lg:flex-row items-center justify-evenly min-h-screen p-5 lg:space-x-4">
          {/* Left Section - Logo, Tagline, and Vector */}
          <div className="flex flex-col items-center  space-y-5 lg:w-1/2">
            <Image
              src={momentix_transparent_logo} // Make sure this variable is defined or use a string path
              alt="logo"
              width={250}
              height={150}
            />
            <h1 className="text-lg font-semibold text-gray-800 text-center lg:text-left">
              Connecting People
            </h1>
            <Image
              src={login_vector} // Make sure this variable is defined or use a string path
              alt="login_vector"
              width={300} // Adjusted size for better alignment
              height={200}
              className="hidden lg:block" // Hide on smaller screens
            />
          </div>

          {/* Right Section - Form and Signup */}
          <div className="flex flex-col items-center space-y-5 w-full lg:w-1/2">
            {/* Login Form Container */}
            {children} {/* Form component will be passed here */}
          </div>
        </div>
      </body>
    </html>
  );
}
