import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import { MobileNavlinks } from "./constants";
import { IoIosNotifications } from "react-icons/io";
import momentix_transparent_logo from "./assets/momentix_transparent_logo.svg";
import Link from "next/link";
import Sidebar from "./components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex bg-grey-50 md:flex-row flex-col h-screen transition-height duration-75 ease-out">
          <div className="hidden md:flex h-screen flex-initial">
            <Sidebar />
          </div>
          {/* Header for small and medium devices */}
          <div className="md:hidden flex flex-row w-full shadow-md bg-white fixed top-0 left-0 right-0 z-10 p-2 justify-between items-center">
            <Link href="/" className="flex px-5 gap-2 w-190 items-center">
              <Image
                src={momentix_transparent_logo}
                alt="logo"
                width={160}
                height={100}
                className="object-contain"
              />
            </Link>
            <Link href="/profile">
              <IoIosNotifications size={30} />
            </Link>
          </div>
          {children}
          <div className="fixed bottom-0 left-0 right-0 md:hidden bg-white shadow-lg py-4 flex justify-around items-center border-t">
            {MobileNavlinks?.map((nav, index) => (
              <Link key={index} href="/" className="flex flex-col items-center">
                {nav?.icon}
              </Link>
            ))}
          </div>
        </div>
      </body>
    </html>
  );
}
