import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import dynamic from "next/dynamic";
import QueryProvider from "./utils/QueryProvider";
const Sidebar = dynamic(() => import("./components/Sidebar"), { ssr: false });
const MobileNav = dynamic(() => import("./components/MobileNav"), {
  ssr: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <QueryProvider>
          <div className="flex bg-grey-50 md:flex-row flex-col h-screen transition-height duration-75 ease-out">
            <div className="hidden md:flex h-screen flex-initial">
              <Sidebar />
            </div>

            {children}
            <MobileNav />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
